application: prj-test
version: 1
runtime: go
api_version: 3

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /css
  static_dir: projecttest/bootstrap/css

- url: /js
  static_dir: projecttest/bootstrap/js

- url: /img
  static_dir: projecttest/bootstrap/img

- url: /.*
  script: _go_app